<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-Lab-Exercises/blob/main/58010_Lab7_Aquino.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **JOHN BENEDICT AQUINO**

# **Activity**

# **Task 1**


Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [4,5,5],
    [7,8,2],
    [1,7,3]
])

B = np.array([
    [6,7,1],
    [4,9,5],
    [4,8,3]
])

C = np.array([
      [6,7,2],
      [3,4,6],
      [3,8,9]
])

X = np.array([
      [5,6,7],
      [1,3,4]
])

In [2]:
A.shape

(3, 3)

In [3]:
X.shape

(2, 3)

In [4]:
X.T #Test of Transposition

array([[5, 1],
       [6, 3],
       [7, 4]])

In [5]:
A @ X.T

array([[85, 39],
       [97, 39],
       [68, 34]])

In [6]:
A @ B 

array([[ 64, 113,  44],
       [ 82, 137,  53],
       [ 46,  94,  45]])

In [7]:
B @ A

array([[ 74,  93,  47],
       [ 84, 127,  53],
       [ 75, 105,  45]])

In [8]:
(A @ B) != (B @ A) #Number 1

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [9]:
A @ (B @ C)

array([[ 855, 1252, 1202],
       [1062, 1546, 1463],
       [ 693, 1058, 1061]])

In [10]:
(A @ B) @ C

array([[ 855, 1252, 1202],
       [1062, 1546, 1463],
       [ 693, 1058, 1061]])

In [11]:
A @ (B @ C) == (A @ B) @ C #Number 2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
A @ (B + C)

array([[118, 201, 127],
       [154, 234, 133],
       [ 82, 153, 116]])

In [13]:
 (A @ B) + (A @ C)

array([[118, 201, 127],
       [154, 234, 133],
       [ 82, 153, 116]])

In [14]:
A @ (B + C) == (A @ B) + (A @ C) #3 already solved.

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
(B + C) @ A

array([[149, 193,  97],
       [130, 216,  94],
       [152, 247, 103]])

In [16]:
B @ A + C @ A

array([[149, 193,  97],
       [130, 216,  94],
       [152, 247, 103]])

In [17]:
(B + C) @ A == B @ A + C @ A #Number 4 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
inv_A = np.linalg.inv(A) #Inverse of A
inv_A


array([[ 0.06666667,  0.13333333, -0.2       ],
       [-0.12666667,  0.04666667,  0.18      ],
       [ 0.27333333, -0.15333333, -0.02      ]])

In [19]:
I = np.array(A @ inv_A, dtype=int) #Identity Matrix
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
A @ I == A #Number 5

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [21]:
empty_set = np.array([
    [[],[],[]],
    [[],[],[]],
    [[],[],[]]
])




In [22]:
A @ empty_set == empty_set #Number 6

array([], shape=(3, 3, 0), dtype=bool)