<a href="https://colab.research.google.com/github/JohnAquino15/Linear-Algebra-Lab-Exercises/blob/main/58010_Lab7_Aquino.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [4,5,5],
    [7,8,2],
    [1,7,3]
])

B = np.array([
    [6,7,1],
    [4,9,5],
    [4,8,3]
])

C = np.array([
      [6,7,2],
      [3,4,6],
      [3,8,9]
])
A @ B #Number 1

array([[ 64, 113,  44],
       [ 82, 137,  53],
       [ 46,  94,  45]])

In [ ]:
B @ A

array([[ 74,  93,  47],
       [ 84, 127,  53],
       [ 75, 105,  45]])

In [ ]:
(A @ B) != (B @ A) #Number 2

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [ ]:
A @ (B @ C)

array([[ 855, 1252, 1202],
       [1062, 1546, 1463],
       [ 693, 1058, 1061]])

In [ ]:
(A @ B) @ C

array([[ 855, 1252, 1202],
       [1062, 1546, 1463],
       [ 693, 1058, 1061]])

In [ ]:
A @ (B @ C) == (A @ B) @ C #Number 3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
A @ (B + C)

array([[118, 201, 127],
       [154, 234, 133],
       [ 82, 153, 116]])

In [ ]:
 (A @ B) + (A @ C)

array([[118, 201, 127],
       [154, 234, 133],
       [ 82, 153, 116]])

In [ ]:
A @ (B + C) == (A @ B) + (A @ C) #Not Included

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
(B + C) @ A

array([[149, 193,  97],
       [130, 216,  94],
       [152, 247, 103]])

In [ ]:
B @ A + C @ A

array([[149, 193,  97],
       [130, 216,  94],
       [152, 247, 103]])

In [ ]:
(B + C) @ A == B @ A + C @ A #Number 4 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [96]:
I = np.identity(3, dtype= int)

In [98]:
A @ I == A #Number 5

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])